[package]
name = "bevy_liquidfun"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.26.0"
bitflags = "2.4.1"
bevy = "0.11"
libliquidfun-sys = { git = "https://github.com/mmatvein/libliquidfun-sys.git" }

[dev-dependencies]
rand = "0.8"